version: "3"
services:
  first-service:
    container_name: first-service
    image: first-service:1.0.0
    build: ./first-service
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - database
    restart: no

  database:
    container_name: database
    image: "postgres:15.2-bullseye"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: no

volumes:
  database-data: